### ISSUE TITLE
metrics-windows-disk-usage.rb incorrect variable

### ISSUE THREAD

**Issue by apangan** [sensu-plugins/sensu-plugins-windows#11]
The following lines should be:

Line 58:  next if config[:ignore_mnt] && config[:ignore_mnt].find { |x| caption.match(x) }
Line 59:  next if config[:include_mnt] && !config[:include_mnt].find { |x| caption.match(x) }

Otherwise you get errors complaining that the variable 'mnt' is not defined.

**Comment by analytically** [comment]
Fixed, released 0.0.8, thanks!
