### ISSUE TITLE
Windows disk space checks do not take into account labels

### ISSUE THREAD

**Issue by michnmi** [sensu-plugins/sensu-plugins-windows#12]
Hi All, I'd like to add the ability to the windows disk check not to check only the mount point (which is the drive letter) but the label of the drive as well. 

Drive letters are randomly assigned by default espacially when usb sticks need to be present (like dongles). In that case ignoring only drive letters is not convenient since it is not consistent . 

There are two ways we could go about this
1) Adding one more line under https://github.com/sensu-plugins/sensu-plugins-windows/blob/master/bin/check-windows-disk.rb#L76 to check the same attributes for label this time or 
2) Adding another flag for label. 

Any preferences?
MM

**Comment by michnmi** [comment]
Also, come to think of it, a better solution would be to sub (mnt) with (mnt,label) in L76 since Driveletter(mnt) and Label(label) will never be the same, as you can't add as a label for a disk, a driveletter. In that case, the ignoremnt flag would search for both. 
MM

**Comment by eheydrick** [comment]
I'd happily take a backwards compatible PR that addresses this.

**Comment by majormoses** [comment]
closed per: https://github.com/sensu-plugins/sensu-plugins-windows/issues/20
