### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by ajeba99** [sensu-plugins/sensu-plugins-windows#15]
I have a question, maybe two, and this seems to be the only place I know where to ask.

As I've become more comfortable using Sensu I've started writing my own checks.  I am a Windows engineer and I've realized I don't need Ruby to create and run a Windows Check.  I wrote one entirely in Powershell and instead of the handler calling Ruby.exe and a .rb script, it's powershell.exe and a .ps1 script.  It returns the data in a format that Graphite can easily understand.

First, why aren't there any non ruby community scripts for Windows metrics and checks?  Or am I missing their location.  And Second, can I create a community repo here that contains these Powershell metrics?  Or should I look elsewhere?

**Comment by ajeba99** [comment]
Some further information:

I've rewritten each Windows metric under /bin to use only Poweshell and return the same information in the same format.  The handler under conf.d for each metric looks something like ...
````
{
  "checks": {
    "metrics-windows-cpu-load": {
      "type": "metric",
      "command": "Powershell.exe -NonInteractive -NoProfile -ExecutionPolicy Bypass -NoLogo C:\\etc\\sensu\\plugins\\metrics-windows-cpu-load.ps1",
      "handlers": [ "graphite" ],
      "subscribers": "windows",
      "interval": 30
    }
  }
}
````

After doing that I ran a nifty Powershell command called "Measure-Command" which gives me the speed at which whatever-it-is I am running.  Below is the measured speed for the Ruby version and the Powershell version of each metric..
````
=====CPU Load=====
Measure-Command { C:\opt\sensu\embedded\bin\ruby.exe C:\etc\sensu\plugins\metrics-windows-cpu-load.rb }
Seconds           : 1
Milliseconds      : 450
Ticks             : 14505758
TotalSeconds      : 1.4505758
TotalMilliseconds : 1450.5758

Measure-Command { C:\etc\sensu\plugins\metrics-windows-cpu-load.ps1 }
Seconds           : 1
Milliseconds      : 7
Ticks             : 10073830
TotalSeconds      : 1.007383
TotalMilliseconds : 1007.383


=====Disk Usage=====
Measure-Command { C:\opt\sensu\embedded\bin\ruby.exe C:\etc\sensu\plugins\metrics-windows-disk-usage.rb }
Seconds           : 0
Milliseconds      : 126
Ticks             : 1263494
TotalSeconds      : 0.1263494
TotalMilliseconds : 126.3494

Measure-Command { C:\etc\sensu\plugins\metrics-windows-disk-usage.ps1 }
Seconds           : 0
Milliseconds      : 22
Ticks             : 220080
TotalSeconds      : 0.022008
TotalMilliseconds : 22.008


=====RAM Usage=====
Measure-Command { C:\opt\sensu\embedded\bin\ruby.exe C:\etc\sensu\plugins\metrics-windows-ram-usage.rb }
Seconds           : 0
Milliseconds      : 706
Ticks             : 7067268
TotalSeconds      : 0.7067268
TotalMilliseconds : 706.7268

Measure-Command { C:\etc\sensu\plugins\metrics-windows-ram-usage.ps1 }
Seconds           : 0
Milliseconds      : 33
Ticks             : 336759
TotalSeconds      : 0.0336759
TotalMilliseconds : 33.6759


=====Uptime=====
Measure-Command { C:\opt\sensu\embedded\bin\ruby.exe C:\etc\sensu\plugins\metrics-windows-uptime.rb }
Seconds           : 1
Milliseconds      : 459
Ticks             : 14591169
TotalSeconds      : 1.4591169
TotalMilliseconds : 1459.1169

Measure-Command { C:\etc\sensu\plugins\metrics-windows-uptime.ps1 }
Seconds           : 1
Milliseconds      : 2
Ticks             : 10023562
TotalSeconds      : 1.0023562
TotalMilliseconds : 1002.3562


=====Network Statistics=====
Measure-Command { C:\opt\sensu\embedded\bin\ruby.exe C:\etc\sensu\plugins\metrics-windows-network.rb };Measure-Command { C:\etc\sensu\plugins\metrics-windows-network.ps1 }

Seconds           : 1
Milliseconds      : 191
Ticks             : 11919659
TotalSeconds      : 1.1919659
TotalMilliseconds : 1191.9659

Seconds           : 1
Milliseconds      : 21
Ticks             : 10218456
TotalSeconds      : 1.0218456
TotalMilliseconds : 1021.8456
````
As you can tell some differences are staggering.

Updating the checks for each Windows check is a simple if else statement to rewrite the output of the metric.

I'd like to share this with the community.  How do I go about doing that here?

**Comment by bgaillard** [comment]
Hi @ajeba99, 

I'm currently having lot of problems with Sensu under Windows :( (see https://github.com/sensu-plugins/sensu-plugins-windows/issues/16, https://github.com/sensu/sensu/issues/1236 and https://github.com/opower/sensu-metrics-relay/issues/28). 

So i'm very interested about your work on pure Powershell check plugins, could you provide me the source code of the `metrics-windows-cpu-load.ps1` file you wrote ? 

I would like to test it to see if it allows to solve some of the problems I encounter.

Thanks for your help.

**Comment by ajeba99** [comment]
Salut @bgaillard,

Pas problem, here is the metric script I sent to clients for Sensu to run ...
````
# Managed by Chef
#
# metric-windows-cpu-load
#
# DESCRIPTION:
# This plugin collects and outputs the CPU Usage in a Graphite acceptable format.
#
# OUTPUT:
# metric data
#
# PLATFORMS:
# Windows
#
# DEPENDENCIES:
# Powershell
#
$All = (Get-Counter -Counter "\Processor(_Total)\% Processor Time" -SampleInterval 1 -MaxSamples 1).CounterSamples
$Value = [Math]::Round($All.CookedValue,2)
$Path = hostname
$Path = $Path.ToLower()
"$Path.system.processor_total.%_processor_time " + $Value + " " + [int][double]::Parse((Get-Date -UFormat %s))
````


Here is the metric event handler json config that is on the Sensu server ...
````
{
  "checks": {
    "metric-windows-cpu-load": {
      "type": "metric",
      "command": "Powershell.exe -NonInteractive -NoProfile -ExecutionPolicy Bypass -NoLogo C:\\etc\\sensu\\plugins\\metric-windows-cpu-load.ps1",
      "handlers": [ "graphite" ],
      "subscribers": [ "windows-clients" ],
      "interval": 30
    }
  }
}
````

Here is my Graphite handler config ...
````
{
  "handlers": {
    "graphite": {
      "type": "tcp",
      "socket": {
        "host": "sensu-server.d.solutionset.com",
        "port": 2003
      },
      "mutator": "only_check_output"
    }
  }
}
````


So, the server publishes a request for a check every 30 seconds.  The client run metric-windows-cpu-load.ps1 and publishes the results to RabbitMQ.  Sensu picks up the result and sends it to Graphite on port 2003 which is the carbon plaint text port.

Ciao,
-Jim

**Comment by bgaillard** [comment]
Hi @ajeba99 and thanks a lot for this ! 

I'll try your Powershell script with one of our customers on Tuesday and we'll give you feedback after. 

@+

Baptiste

**Comment by eheydrick** [comment]
There is a repository of Powershell checks over at https://github.com/carllindelof/sensu-checks.

**Comment by ajeba99** [comment]
@eheydrick Understood.  It good to see I am not the only Windows person who's taken the initiative to write Pure Powershell checks.  I am sure there are more.

My point is, why not incorporate those examples and my examples into the community repo somewhere?  This is the most likely place where new and existing users will look for metrics and checks.  I proven these Ruby checks are slower and more CPU intensive.  Also, it's my belief ruby-based Windows metrics and checks are less likely for Windows user adoption.

**Comment by ajeba99** [comment]
You can find my metrics and checks at https://github.com/ajeba99/Sensu-Windows-Plugins .

**Comment by bgaillard** [comment]
@ajeba99 just wanted to thank you for this merge, was in holidays so that's why i'm responding so late :-).
