### ISSUE TITLE
Several plugins do not work on localized machines (for exemple French)

### ISSUE THREAD

**Issue by bgaillard** [sensu-plugins/sensu-plugins-windows#16]
Hi, i'm begining to use Sensu to monitor Windows machines for one of our customer. 

I have a Windows 10 Operating System which is configured in French. 

On this environment the following plugins do not work : 
- `check-windows-cpu-load.rb`
- `metrics-windows-cpu-load.rb`
- `check-windows-ram.rb`
- `metrics-windows-ram.rb`

The problem is caused by the fact that the [`typeperf`](https://technet.microsoft.com/en-us/library/bb490960.aspx) command uses counter names which are localized. 

For example in English we have a counter named `% processor time` but in French the name is `% temps processeur` (as a reminder the list of performance counters can be get using the [`Get-Counter`](https://technet.microsoft.com/library/hh849685.aspx) command).

As a consequence executing the following command fails on a Windows 10 OS configured in French.

```
typeperf “\processor(_Total)\% Processor Time”
z patienter...
Erreur : aucun compteur valide.
```

To make it work in French we have to use the following command instead.

```
typeperf “\processeur(_total)\% temps processeur"
"(PDH-CSV 4.0)","\\BOUBA-PC\processeur(_total)\% temps processeur"
"04/15/2016 11:56:43.111","64.303526"
"04/15/2016 11:56:44.113","3.294592"
"04/15/2016 11:56:45.115","1.919966"
"04/15/2016 11:56:46.116","1.896460"
"04/15/2016 11:56:47.117","1.844883"
"04/15/2016 11:56:48.118","0.321891"
"04/15/2016 11:56:49.120","0.374646"
"04/15/2016 11:56:50.121","0.502694"
"04/15/2016 11:56:51.123","1.710701"
"04/15/2016 11:56:52.124","0.852081"
                         z patienter...
L’opération s’est bien déroulée.
```

This problem is also described here https://www.zabbix.com/forum/showthread.php?t=7455 and here https://support.microsoft.com/en-us/kb/287159.

I'll provide a PR to fix this, the trick is to identify patterns in the help output by the `typeperf -h` command, for example. 

``` ruby
language = 'English'

# Trick to know in which language is the current system
help = IO.popen('typeperf -h').readlines.join("")

if help.include? "Compteurs de performances"
    language = 'French'
end

# Call different 'typeperf' commands depending on the language in use on the system
case language
    when 'English'
        io = IO.popen('typeperf -sc 1 "processor(_total)\\% processor time"')
    when 'French'
        io = IO.popen('typeperf -sc 1 "processeur(_total)\\% temps processeur"')
end
```

Do you think those modifications are good ? 

Thx

**Comment by majormoses** [comment]
I am thinking we want to go with something like what I outlined here: https://github.com/sensu-plugins/sensu-plugins-windows/pull/17#issuecomment-305680112

**Comment by mbbroberg** [comment]
@bgaillard any chance you're up for reviewing the fix in #47?

**Comment by majormoses** [comment]
closed via #47

**Comment by Koxx3** [comment]
Ok, here are my tests of Powershell scripts on a Windows 10 64bits FR.

Those scripts doesn't work : 
check-windows-disk-writeable.ps1
check-windows-disk.ps1 -c 1 -w 2
check-windows-pagefile.ps1 -c 1 -w 2
check-windows-ram.ps1 -c 1 -w 2
metric-windows-disk-usage.ps1 -c 1 -w 2
metric-windows-network.ps1 -c 1 -w 2
metric-windows-ram-usage.ps1 -c 1 -w 2


[test.log](https://github.com/sensu-plugins/sensu-plugins-windows/files/1836820/test.log)

**Comment by Koxx3** [comment]
for memeory, this seems to work : 
`Get-WmiObject win32_operatingsystem -ComputerName $c |
                   Foreach {"{0:N2}" -f ((($_.TotalVisibleMemorySize - $_.FreePhysicalMemory)*100)/ $_.TotalVisibleMemorySize)}`

**Comment by Koxx3** [comment]
ok ... forget it.
It was a firewall issue (Comodo firewall).
sorry

**Comment by majormoses** [comment]
closing per https://github.com/sensu-plugins/sensu-plugins-windows/issues/16#issuecomment-375244544
