### ISSUE TITLE
release latest changes?

### ISSUE THREAD

**Issue by andyroyle** [sensu-plugins/sensu-plugins-windows#31]
Hi guys,

Any chance we can get the latest changes released to rubygems.org? 

Cheers!

**Comment by eheydrick** [comment]
Working on getting a new release out. There's been a lot of changes so it'll take a bit longer than usual.

**Comment by andyroyle** [comment]
👍

**Comment by majormoses** [comment]
I have made several releases recently:
- https://rubygems.org/gems/sensu-plugins-windows/versions/0.1.0
- https://rubygems.org/gems/sensu-plugins-windows/versions/1.0.0
- https://rubygems.org/gems/sensu-plugins-windows/versions/2.0.0
