### ISSUE TITLE
check-windows-ram.rb

### ISSUE THREAD

**Issue by if-meaton** [sensu-plugins/sensu-plugins-windows#35]
Hi,

The above plugin reports the following error, but only on one of my servers:

output Check failed to run: undefined method `length' for nil:NilClass, ["c:/opt/sensu/plugins/check-windows-ram.rb:45:in `acquire_ram_usage'", "c:/opt/sensu/plugins/check-windows-ram.rb:54:in `run'", "c:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.

It's a Windows Server. 2003 Standard 32bit with Service Pack 2.

Not sure what other details you need?

Thanks,

Michael

**Comment by dplusf** [comment]
Hi @if-meaton 

i am very optimistic that you dont have a english languagepack on that particular server.
i ve had the same problem. the cause is the typeperf command wich will look for english named counters wich are not known on servers with other languages installed. 

Best
Dennis

**Comment by if-meaton** [comment]
Hey,

The perf counters where corrupt, i ran this:

C:\Windows\System32>lodctr /R

Info: Successfully rebuilt performance counter setting from system backup store

which fixed my issue.

Thanks,

Michael

**Comment by majormoses** [comment]
@if-meaton any chance we could get you to put a PR to document this in the readme?

**Comment by Rayco** [comment]
Hi,

I have the same problem.

This is my check:

`
"cpu-load": {
            "handlers": ["mailer"],
            "command": "c:\\opt\\sensu\\embedded\\bin\\ruby c:\\opt\\sensu\\embedded\\bin\\check-windows-cpu-load.rb -w 80 -c 90",
            "interval": 60,
            "occurrences": 5,
            "subscribers": [ "windows" ]
        },
`

`
Check failed to run: undefined method `length' for nil:NilClass, ["c:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-windows-2.2.1/bin/check-windows-ram.rb:45:in `acquire_ram_usage'", "c:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-windows-2.2.1/bin/check-windows-ram.rb:54:in `run'", "c:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
`

Windows Server 2012 R2.

Thanks

**Comment by majormoses** [comment]
This has been documented in #64 if there is anything else to do please respond back and we can open the issue.
