### ISSUE TITLE
Having issues with with checks working 

### ISSUE THREAD

**Issue by downright770** [sensu-plugins/sensu-plugins-windows#54]
This is on a Windows 2016 server 
I'm able to run checks from cmd line here is an example 

{
  "checks": {
    "check_win_process_jobmgr": {
      "command": "C:\opt\sensu\plugins\sensu-plugins-windows-master\bin\check_windows-process -p JobMgr.exe",
      "subscribers": [
        "Windows"
      ],
      "interval": 10
    }
  }
}

 Here is the log file output.

{"timestamp":"2017-12-18T16:02:49.797875-0800","level":"warn","message":"config file does not exist or is not readable","file":"C:\\opt\\sensu\\config.json"}
{"timestamp":"2017-12-18T16:02:49.798875-0800","level":"warn","message":"ignoring config file","file":"C:\\opt\\sensu\\config.json"}
{"timestamp":"2017-12-18T16:02:49.798875-0800","level":"warn","message":"loading config files from directory","directory":"C:\\opt\\sensu\\conf.d"}
{"timestamp":"2017-12-18T16:02:49.798875-0800","level":"warn","message":"loading config file","file":"C:/opt/sensu/conf.d/check_win_process_jobmgr.json"}
{"timestamp":"2017-12-18T16:02:49.798875-0800","level":"fatal","message":"config file must be valid json","file":"C:/opt/sensu/conf.d/check_win_process_jobmgr.json","error":"invalid escaped character at line 4, column 22 [parse.c:280]"}
{"timestamp":"2017-12-18T16:02:49.798875-0800","level":"fatal","message":"SENSU NOT RUNNING!"}

I've tried changing the json configuration to c:\\ c\\ can't seem to get it to work but from cmdline it does. any help would be great. 

Thank you

**Comment by absolutejam** [comment]
Can you please try either double backslashes or forward slashes in your json?

For example:
```
c:\\sensu\\plugins\\check-foo.rb
```
or
```
c:/sensu/plugins/check-foo.rb
```

The former is ore bulletproof as it passes the path you want as json uses `\` as an escape char, meaning `\\` is escaping the `\`), but forward-slashes work the majority of the time.

**Comment by downright770** [comment]
yeah that works 
Thank you

**Comment by downright770** [comment]
Have you have come across issues with Windows client not sending information to Sensu server (RH7).
I have the checks on the Windows client  and there not throwing errors but don't send information back. I have also tired adding the checks on the Sensu server it's self and subscribe Windows client to it.

**Comment by cwjohnston** [comment]
@downright770 looks like the original problem here was solved and it's been some time since the last post so I am closing this issue. 

If you need more general troubleshooting assistance, please check out our highly helpful community [Slack team](https://slack.sensu.io) and [Discourse forums](https://discourse.sensu.io)!
