### ISSUE TITLE
metric-windows-network.ps1 - You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by csoleimani** [sensu-plugins/sensu-plugins-windows#72]
Getting this error when running  metric-windows-network.ps1:

```
You cannot call a method on a null-valued expression.At C:\opt\sensu\embedded\lib\ruby\gems\2.4.0\gems\sensu-plugins-windows-2.9.0\bin\powershell\metric-windows-network.ps1:53 char:7
```

**Comment by csabo** [comment]
@csoleimani it looks like you closed your PR, did you get your issue resolved?

**Comment by samroy92** [comment]
I have the same issue as described above.

**Comment by csoleimani** [comment]
Whoops, I forgot to respond to this. I have not seen this issue for a while, but I'm not sure how we resolved it in our environment.

**Comment by eike-spiller** [comment]
Hi, still an issue over here.

c:\\opt\\sensu\\embedded\\bin\\ruby C:\\opt\\sensu\\embedded\\bin\\powershell_helper.rb windows-metric-network.ps1

does produce this.

c:\\opt\\sensu\\embedded\\bin\\ruby C:\\opt\\sensu\\embedded\\bin\\metric-windows-network.rb

does work. So ruby OK, powershell NOT. directly using powershell, like "powershell.exe -ExecutionPolicy ByPass -C metric-windows-network.ps1" has the same issue btw.


Other checks are ok. Would be nice if this will be resolved.

**Comment by eike-spiller** [comment]
Oh, got it. You have to submit the first param to that function.

In case you just want all network adapters and FQDN names, you can use my stripped down version:

`$ThisProcess = Get-Process -Id $pid
$ThisProcess.PriorityClass = "BelowNormal"

. (Join-Path $PSScriptRoot perfhelper.ps1)

$Hostname = [System.Net.Dns]::GetHostEntry([string]"localhost").HostName.toLower()


$perfCategoryID = Get-PerformanceCounterByID -Name 'Network Interface'
$localizedCategoryName = Get-PerformanceCounterLocalName -ID $perfCategoryID

foreach ($ObjNet in (Get-Counter -Counter "\$localizedCategoryName(*)\*").CounterSamples)
{
     $Measurement = ($ObjNet.Path).Trim("\\") -replace "\\","." -replace " ","_" -replace "[(]","." -replace "[)]","" -rep\
lace "[\{\}]","" -replace "[\[\]]",""

     $Measurement = $Measurement.Remove(0,$Measurement.IndexOf("."))
     $Path = $Hostname+$Measurement

     $Path = $Path.Replace("/s","_per_second")
     $Path = $Path.Replace(":","")
     $Path = $Path.Replace(",","")
     $Path = $Path.Replace("ä","ae")
     $Path = $Path.Replace("ö","oe")
     $Path = $Path.Replace("ü","ue")
     $Path = $Path.Replace("ß","ss")

     $Value = [System.Math]::Round(($ObjNet.CookedValue),0)
     $Time = DateTimeToUnixTimestamp -DateTime (Get-Date)

     Write-Host "$Path $Value $Time"
}`


This is working for me now.

**Comment by maxadamo** [comment]
@eike-spiller you have a line wrapped which doesn't seem to make a correct escape. 
Apart from this small issue, it works properly. Thanks
