### ISSUE TITLE
Windows client debug

### ISSUE THREAD

**Issue by jbruns2015** [sensu-plugins/sensu-plugins-windows#78]
Does anyone know how to turn on debug in Windows for Sensu client?  I need to see why it is not firing off the script and the regular log (sensu-client.log) has zero help.

**Comment by jbruns2015** [comment]
Installed the latest sensu client sensu-1.7.0-1-x64.msi and still same issue.  File sensu-client.out.log has no indicators that it is not firing off a plugins script.  The log does indicate that it is loading the config file ok.

Any help would be very appreciated.

**Comment by majormoses** [comment]
This would best be handled in the main sensu repo, this repo purely for checks which.

**Comment by jbruns2015** [comment]
What is the repo for the main sensu?

**Comment by majormoses** [comment]
https://github.com/sensu/sensu
