### ISSUE TITLE
metrics-windows-network.rb bug

### ISSUE THREAD

**Issue by ajeba99** [sensu-plugins/sensu-plugins-windows#9]
Believe me now, hear me later ... yah ...

Line 60 of sensu-plugins-windows/bin/metrics-windows-network.rb should read ...

name = [config[:scheme], ifz_name, metric].join('.').gsub(' ', '_').tr('{}', '').tr('[]','')

... adding the additional .tr at the end.

This is because if an Intel Network Adapter stupidly has a [R] trademark in the name/description it will break the metric showing up in Graphite/Grafana.

Enjoy.

**Comment by eheydrick** [comment]
Wow, that's nutty. Can you open a pull request with the fix and we'll get that updated.

**Comment by ajeba99** [comment]
Sure, also to add, that [R] can sometimes be seen as a (R).  More specifically that can be the actual issue but removing the [] fixes it.

**Comment by eheydrick** [comment]
Fixed in [0.0.7](https://rubygems.org/gems/sensu-plugins-windows/versions/0.0.7). Thanks again for the report and the fix.
